In [ ]:
## data visualization lab week-5

In [3]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns",None)
pd.set_option("Display.width",1000)
print("Environment ready!")

Environment ready!

## create csv file

In [4]:
demo_data=pd.DataFrame({
"device_id":["D1","D2","D3","D4","D5"],
"temperature":[28,-1,30,95,29],
"humidity":[65,70,-1,68,20],
"pressure":[1012,1013,-1,1011,500]})
print(demo_data)

  device_id  temperature  humidity  pressure
0        D1           28        65      1012
1        D2           -1        70      1013
2        D3           30        -1        -1
3        D4           95        68      1011
4        D5           29        20       500

## write to csv using to_csv()

In [5]:
demo_data.to_csv("Demo_SensorData.csv",index=False)
print("Demo_SensorData.csv created")

Demo_SensorData.csv created

## step 2 load data (csv to dataframe)

In [6]:
df=pd.read_csv("Demo_SensorData.csv")
print(df)

  device_id  temperature  humidity  pressure
0        D1           28        65      1012
1        D2           -1        70      1013
2        D3           30        -1        -1
3        D4           95        68      1011
4        D5           29        20       500

In [7]:
df.shape

(5, 4)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   device_id    5 non-null      object
 1   temperature  5 non-null      int64
 2   humidity     5 non-null      int64
 3   pressure     5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 288.0+ bytes

In [9]:
df.describe() #basic statistics

       temperature   humidity     pressure
count     5.000000   5.000000     5.000000
mean     36.200000  44.400000   707.000000
std      35.351096  32.761258   453.649093
min      -1.000000  -1.000000    -1.000000
25%      28.000000  20.000000   500.000000
50%      29.000000  65.000000  1011.000000
75%      30.000000  68.000000  1012.000000
max      95.000000  70.000000  1013.000000

## step2b 5-Number summary

In [10]:
numeric_cols=["temperature","humidity","pressure"]
df[numeric_cols].quantile([0,0.25,0.5,0.75,1.0])

      temperature  humidity  pressure
0.00         -1.0      -1.0      -1.0
0.25         28.0      20.0     500.0
0.50         29.0      65.0    1011.0
0.75         30.0      68.0    1012.0
1.00         95.0      70.0    1013.0

In [12]:
df[numeric_cols].max()

temperature      95
humidity         70
pressure       1013
dtype: int64

In [13]:
df[numeric_cols].median()

temperature      29.0
humidity         65.0
pressure       1011.0
dtype: float64

In [22]:
(df[numeric_cols]== -1).sum()

temperature    1
humidity       1
pressure       1
dtype: int64

## replace missing values use mean

In [24]:
df_mean_cleaned=df.copy()
for col in numeric_cols:
    mean_value=df_mean_cleaned.loc[df_mean_cleaned[col]!= -1, col].mean()
    df_mean_cleaned[col]= df_mean_cleaned[col].replace(-1,mean_value)
df_mean_cleaned

  device_id  temperature  humidity  pressure
0        D1         28.0     65.00      1012
1        D2         45.5     70.00      1013
2        D3         30.0     55.75       884
3        D4         95.0     68.00      1011
4        D5         29.0     20.00       500

In [25]:
print("missing place holder counts after mean replacement:")
print((df_mean_cleaned[numeric_cols]== -1).sum())
print("\n5-number summary after missing treatment:")
df_mean_cleaned[numeric_cols].quantile([0,0.25,0.5,0.75,1.0])

missing place holder counts after mean replacement:
temperature    0
humidity       0
pressure       0
dtype: int64

5-number summary after missing treatment:

      temperature  humidity  pressure
0.00         28.0     20.00     500.0
0.25         29.0     55.75     884.0
0.50         30.0     65.00    1011.0
0.75         45.5     68.00    1012.0
1.00         95.0     70.00    1013.0

In [26]:
df_final=df_mean_cleaned.copy()
for col in numeric_cols:
    median_value=df_final[col].median()
    df_final.loc[df_final[col] > median_value*3, col]=median_value
df_final

  device_id  temperature  humidity  pressure
0        D1         28.0     65.00      1012
1        D2         45.5     70.00      1013
2        D3         30.0     55.75       884
3        D4         30.0     68.00      1011
4        D5         29.0     20.00       500

In [27]:
print("before cleaning (treat -1 as NaN for summary):")
display(df[numeric_cols].replace(-1,np.nan).quantile([0,0.25,0.5,0.75,1.0]))

print("\nafter missing value handling:")
display(df_mean_cleaned[numeric_cols].quantile([0,0.25,0.5,0.75,1.0]))

print("\nafter noise handling:")
display(df_final[numeric_cols].quantile([0,0.25,0.5,0.75,1.0]))

before cleaning (treat -1 as NaN for summary):

      temperature  humidity  pressure
0.00        28.00     20.00    500.00
0.25        28.75     53.75    883.25
0.50        29.50     66.50   1011.50
0.75        46.25     68.50   1012.25
1.00        95.00     70.00   1013.00

after missing value handling:

      temperature  humidity  pressure
0.00         28.0     20.00     500.0
0.25         29.0     55.75     884.0
0.50         30.0     65.00    1011.0
0.75         45.5     68.00    1012.0
1.00         95.0     70.00    1013.0

after noise handling:

      temperature  humidity  pressure
0.00         28.0     20.00     500.0
0.25         29.0     55.75     884.0
0.50         30.0     65.00    1011.0
0.75         30.0     68.00    1012.0
1.00         45.5     70.00    1013.0

In [29]:
df_final.to_csv("demo_Sensor_cleaned.csv",index=False)
print("cleaned csv file saved")

cleaned csv file saved