# Demo 4: Pandas, Data loading, Storage and File formats

In [2]:
import pandas as pd
import numpy as np

### Q1. Create a Series from a list of integers representing daily temperatures (in Celsius) over a week. Assign index labels as day of the week.

In [3]:
temp = [31,32,31,30,34,32,31]
day = ["Monday", "Tuesday", "wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
data = pd.Series(temp, index=day, name="Temp")
df = pd.DataFrame(data)
df

           Temp
Monday       31
Tuesday      32
wednesday    31
Thursday     30
Friday       34
Saturday     32
Sunday       31

> a. Find and print the average (mean) temperature for the week.

In [4]:
print("Mean: ", df["Temp"].mean())

Mean:  31.571428571428573

> b. Identify and print the maximum and minimum temperatures and their respective days.

In [5]:
print("Maximum is: ", df["Temp"].max())
print("Minimum is: ", df["Temp"].min())

Maximum is:  34
Minimum is:  30

> c. Display the temperatures greater than a specific value.

In [6]:
print("Your results are:\n", df[df["Temp"]>int(input("Enter the min temp: "))])

Your results are:
         Temp
Friday    34

> d. Convert all temperatures to Fahrenheit.

In [7]:
df["Temp in F"]=df["Temp"]*1.8+3
print("Your results are:\n", df[["Temp", "Temp in F"]])

Your results are:
            Temp  Temp in F
Monday       31       58.8
Tuesday      32       60.6
wednesday    31       58.8
Thursday     30       57.0
Friday       34       64.2
Saturday     32       60.6
Sunday       31       58.8

> e. Print the days had temperatures above the average.

In [8]:
print("Days with Temp above average are:\n", df[df["Temp"]>df["Temp"].mean()])

Days with Temp above average are:
           Temp  Temp in F
Tuesday     32       60.6
Friday      34       64.2
Saturday    32       60.6

### 2. Create a data frame with details of 10 students and columns as Roll Number, Name, Gender, Marks1, Marks2, Marks3.

In [9]:
data = {
    "Roll Number": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Name": ["Aarav", "Diya", "Rohan", "Ananya", "Karan", "Meera", "Arjun", "Pooja", "Rahul", "Sneha"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "Marks1": [78, 85, 67, 90, 4, 88, 80, 76, 69, 92],
    "Marks2": [82, 20, 70, 88, 2, 91, 84, 73, 9, 89],
    "Marks3": [74, 88, 65, 92, 3, 86, 81, 79, 71, 90]
}
df = pd.DataFrame(data)
df

   Roll Number    Name Gender  Marks1  Marks2  Marks3
0            1   Aarav      M      78      82      74
1            2    Diya      F      85      20      88
2            3   Rohan      M      67      70      65
3            4  Ananya      F      90      88      92
4            5   Karan      M       4       2       3
5            6   Meera      F      88      91      86
6            7   Arjun      M      80      84      81
7            8   Pooja      F      76      73      79
8            9   Rahul      M      69       9      71
9           10   Sneha      F      92      89      90

> a. Create a new column with total marks

In [10]:
df["Total_Marks"] = df["Marks1"]+df["Marks2"]+df["Marks3"]
df

   Roll Number    Name Gender  Marks1  Marks2  Marks3  Total_Marks
0            1   Aarav      M      78      82      74          234
1            2    Diya      F      85      20      88          193
2            3   Rohan      M      67      70      65          202
3            4  Ananya      F      90      88      92          270
4            5   Karan      M       4       2       3            9
5            6   Meera      F      88      91      86          265
6            7   Arjun      M      80      84      81          245
7            8   Pooja      F      76      73      79          228
8            9   Rahul      M      69       9      71          149
9           10   Sneha      F      92      89      90          271

> b. Find the lowest marks in Marks1

In [11]:
print("Lowest marks in Marks1 are: ", df["Marks1"].min())

Lowest marks in Marks1 are:  4

> c. Find the Highest marks in Marks2

In [12]:
print("Lowest marks in Marks2 are: ", df["Marks2"].max())

Lowest marks in Marks2 are:  91

> d. Find the average marks in Marks3

In [13]:
print("Average marks in Marks3 are: ", df["Marks3"].mean())

Average marks in Marks3 are:  72.9

> e. Find student name with highest average

In [22]:
df.nlargest(1, "Total_Marks")

   Roll Number   Name Gender  Marks1  Marks2  Marks3  Total_Marks
9           10  Sneha      F      92      89      90          271

In [15]:
print("Average marks in Marks3 are:\n", df.loc[df[["Marks1", "Marks2", "Marks3"]].mean(axis=1).idxmax()])

Average marks in Marks3 are:
 Roll Number       10
Name           Sneha
Gender             F
Marks1            92
Marks2            89
Marks3            90
Total_Marks      271
Name: 9, dtype: object

> f. Find how many students failed in Marks2 (<40)`

In [16]:
print("Count of students failing in Marks2: ", (df["Marks2"]<40).sum())

Count of students failing in Marks2:  3