In [1]:
# Name: Chhayank Sharma
# Registration no.: 60
# Demo given to introduce data preperation basics for DAV lab

In [2]:
import numpy as np
import pandas as pd

In [3]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
string_data = pd.Series(["aaaaaaaaaaa", np.nan, None, "abcdefghij"])
string_data

0    aaaaaaaaaaa
1            NaN
2           None
3     abcdefghij
dtype: object

In [5]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [6]:
string_data.notna()

0     True
1    False
2    False
3     True
dtype: bool

In [7]:
data1 = pd.Series([1, np.nan, 3.5, np.nan, 7])
data1

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [8]:
data1.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [9]:
data2 = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data2

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data2.dropna(axis="columns", how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [13]:
df3 = pd.DataFrame(np.random.standard_normal((7, 3)))
df3.iloc[:4, 1] = np.nan
df3.iloc[:2, 2] = np.nan
df3.fillna(0)

          0         1         2
0 -0.364005  0.000000  0.000000
1 -0.180156  0.000000  0.000000
2  1.383894  0.000000 -0.799769
3 -0.475592  0.000000  1.360946
4 -0.772926  1.470959 -0.725839
5 -0.721958 -1.097118 -0.022592
6 -0.865666  1.407778 -0.045018

In [15]:
df4 = pd.DataFrame(np.random.standard_normal((7, 3)))
df4.iloc[:4, 1] = np.nan
df4.iloc[:2, 2] = np.nan
df4

          0         1         2
0 -0.230385       NaN       NaN
1 -0.449754       NaN       NaN
2  0.602017       NaN -0.578566
3 -0.253461       NaN  0.599191
4 -1.129581 -1.742323  0.195112
5  1.382058 -0.299890  0.102412
6  0.492760  0.019437  0.232864

In [16]:
df4.fillna(df4.mean())

          0         1         2
0 -0.230385 -0.674258  0.110202
1 -0.449754 -0.674258  0.110202
2  0.602017 -0.674258 -0.578566
3 -0.253461 -0.674258  0.599191
4 -1.129581 -1.742323  0.195112
5  1.382058 -0.299890  0.102412
6  0.492760  0.019437  0.232864

In [17]:
data = pd.DataFrame({
    'A': [1, -999, 3, -1000],
    'B': [-1000, 5, -999, 7]
})
print(data)
data.replace([-999.0,-1000], np.nan, inplace=True) 
print(data)

      A     B
0     1 -1000
1  -999     5
2     3  -999
3 -1000     7
     A    B
0  1.0  NaN
1  NaN  5.0
2  3.0  NaN
3  NaN  7.0

In [18]:
data.fillna(data.median())

     A    B
0  1.0  6.0
1  2.0  5.0
2  3.0  6.0
3  2.0  7.0

In [27]:
data5 = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})
data5

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [28]:
data5.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [21]:
data5.drop_duplicates(subset=["k1"])

    k1  k2
0  one   1
1  two   1

In [29]:
data = pd.DataFrame({"food": ["salt", "bread", "butter",
                              "rice", "chips", "biscuits",
                              "chocolate", "honey", "sugar"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

        food  ounces
0       salt     4.0
1      bread     3.0
2     butter    12.0
3       rice     6.0
4      chips     7.5
5   biscuits     8.0
6  chocolate     3.0
7      honey     5.0
8      sugar     6.0

In [30]:
food_to_type = {
  "salt": "condiment",
  "bread": "breakfast",
  "butter": "condiment",
  "rice": "grocery",
  "chips": "snack",
  "honey": "condiment",
  "sugar": "condiment",
  "chocolate": "snack"
}

In [31]:
data["ftype"] = data["food"].map(food_to_type)
data

        food  ounces      ftype
0       salt     4.0  condiment
1      bread     3.0  breakfast
2     butter    12.0  condiment
3       rice     6.0    grocery
4      chips     7.5      snack
5   biscuits     8.0        NaN
6  chocolate     3.0      snack
7      honey     5.0  condiment
8      sugar     6.0  condiment

In [34]:
df = pd.DataFrame({
    "Student": ["Amit", "Bella", "Chris", "Nazli"],
    "Maths": [85, 88, 90, 78],
    "Science": [88, 72, 74, 81],
    "English": [78, 81, 84, 83]
})
df = df.set_index("Student")
df

         Maths  Science  English
Student
Amit        85       88       78
Bella       88       72       81
Chris       90       74       84
Nazli       78       81       83

In [33]:
data = pd.DataFrame(np.random.standard_normal((10, 3)))
print(data)
data.describe()

          0         1         2
0 -1.293550 -0.466060  0.776759
1  0.080420 -0.478195 -0.359774
2 -0.787529  0.296017  0.854743
3  0.921208  0.508196 -0.666551
4 -0.868861 -0.305241 -0.595390
5  0.519233  0.755661 -0.489576
6 -0.616115  0.156405 -0.606279
7  0.291805  0.186260 -1.606671
8 -0.717248 -0.850669 -0.344145
9 -1.998988 -0.386653 -1.250430

               0          1          2
count  10.000000  10.000000  10.000000
mean   -0.446962  -0.058428  -0.428732
std     0.891346   0.511438   0.767008
min    -1.998988  -0.850669  -1.606671
25%    -0.848528  -0.446208  -0.651483
50%    -0.666681  -0.074418  -0.542483
75%     0.238959   0.268577  -0.348053
max     0.921208   0.755661   0.854743

In [39]:
col = data[2]
print(col)
print(col[col>col.mean()])
print(col[col.abs()>0.5])

0    0.776759
1   -0.359774
2    0.854743
3   -0.666551
4   -0.595390
5   -0.489576
6   -0.606279
7   -1.606671
8   -0.344145
9   -1.250430
Name: 2, dtype: float64
0    0.776759
1   -0.359774
2    0.854743
8   -0.344145
Name: 2, dtype: float64
0    0.776759
2    0.854743
3   -0.666551
4   -0.595390
6   -0.606279
7   -1.606671
9   -1.250430
Name: 2, dtype: float64

In [37]:
dc = data.copy()

In [42]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                  'data1': range(6)})
print(df)
pd.get_dummies(df['key'], dtype=float)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

     a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0