## DATA VISUALISATION WEEK 4
TOPIC: pandas-series,dataframes,loading/saving
NAME: Riya Agrawal
CLASS: PF
ROLL NO: 46
REG NO: 251090052030

### IMPORTS + VERSION CHECK

In [2]:
import numpy as np
import pandas as pd
print("numpy:",np.__version__)
print("pandas:",pd.__version__)

numpy: 1.21.5
pandas: 1.4.4

In [4]:
ser_x=pd.Series([4,7,-5,-3])
ser_x

0    4
1    7
2   -5
3   -3
dtype: int64

In [7]:
ser_y= pd.Series([4,7,-5,3],index=["d","b","a","c"])
ser_y

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
values=[10,20,30,40]
labels=["A","B","C","D"]
S=pd.Series(values,index=labels)
S

A    10
B    20
C    30
D    40
dtype: int64

In [11]:
## INSPECTING A SERIES
print("index:",S.index)
print("Values:",S.values)

index: Index(['A', 'B', 'C', 'D'], dtype='object')
Values: [10 20 30 40]

In [12]:
## aggregation functions
## pandas provide built in function to summarize data
print("mean:",S.mean())
print("max:",S.max())
print("min:",S.min())

mean: 25.0
max: 40
min: 10

In [14]:
S.idxmax()

'D'

In [15]:
S.idxmin()

'A'

In [16]:
## conditional selection
##conditional create a true/false mask, this mask helps to filter the data
S>20

A    False
B    False
C     True
D     True
dtype: bool

In [19]:
## vectorized operations
## pandas provide operations to apply to all the values at once
S*2

A    20
B    40
C    60
D    80
dtype: int64

In [25]:
## pandas dataframe
## A dataframe is a table with rows and columns
data={
    "Name":["A","B","C","D","E","F","G"],
    "Score1":[50,60,70,80,90,10,20],
    "Score2":[55,65,75,85,95,15,25],
    "Score3":[54,64,74,84,94,14,24],
    "Score4":[53,63,73,83,93,13,23],
    "Score5":[52,62,72,82,92,12,22],
    "Score6":[51,61,71,81,91,11,21],
    "Score7":[57,67,77,87,97,17,27]
}
df=pd.DataFrame(data)
df

  Name  Score1  Score2  Score3  Score4  Score5  Score6  Score7
0    A      50      55      54      53      52      51      57
1    B      60      65      64      63      62      61      67
2    C      70      75      74      73      72      71      77
3    D      80      85      84      83      82      81      87
4    E      90      95      94      93      92      91      97
5    F      10      15      14      13      12      11      17
6    G      20      25      24      23      22      21      27

In [23]:
## INSPECTING A DATAFRAME
df.head()

  Name  Score1  Score2
0    A      50      55
1    B      60      65
2    C      70      75

In [26]:
df.head()

  Name  Score1  Score2  Score3  Score4  Score5  Score6  Score7
0    A      50      55      54      53      52      51      57
1    B      60      65      64      63      62      61      67
2    C      70      75      74      73      72      71      77
3    D      80      85      84      83      82      81      87
4    E      90      95      94      93      92      91      97

In [27]:
print(df.shape)
print(df.columns)

(7, 8)
Index(['Name', 'Score1', 'Score2', 'Score3', 'Score4', 'Score5', 'Score6',
       'Score7'],
      dtype='object')

In [28]:
df["Score1"]

0    50
1    60
2    70
3    80
4    90
5    10
6    20
Name: Score1, dtype: int64

In [29]:
df["Name"]

0    A
1    B
2    C
3    D
4    E
5    F
6    G
Name: Name, dtype: object

In [30]:
df["Total"]=df["Score1"]+df["Score2"]
df

  Name  Score1  Score2  Score3  Score4  Score5  Score6  Score7  Total
0    A      50      55      54      53      52      51      57    105
1    B      60      65      64      63      62      61      67    125
2    C      70      75      74      73      72      71      77    145
3    D      80      85      84      83      82      81      87    165
4    E      90      95      94      93      92      91      97    185
5    F      10      15      14      13      12      11      17     25
6    G      20      25      24      23      22      21      27     45

In [33]:
df[df["Score1"]>55]

  Name  Score1  Score2  Score3  Score4  Score5  Score6  Score7  Total
1    B      60      65      64      63      62      61      67    125
2    C      70      75      74      73      72      71      77    145
3    D      80      85      84      83      82      81      87    165
4    E      90      95      94      93      92      91      97    185

In [34]:
## data loading and storage
## load tab separated file
df_temps=pd.read_csv("week4.tsv",sep='\t')
df_temps

    Day  temp_C
0   mon      28
1   tue      29
2   wed      31
3  thur      30
4   fri      27
5   sat      25
6   sun      29

In [44]:
temp_series=pd.Series(df_temps["temp_C"].values,index=df_temps["Day"])
temp_series

Day
mon     28
tue     29
wed     31
thur    30
fri     27
sat     25
sun     29
dtype: int64

In [46]:
print("max:",temp_series.max())
print("Min:",temp_series.min())
print("index of max:",temp_series.idxmax())
print(temp_series[temp_series>29])

max: 31
Min: 25
index of max: wed
Day
wed     31
thur    30
dtype: int64

In [48]:
df=pd.read_csv("scores.csv")
df

   ID   Name  Score
0   1   Asha     78
1   2   Ravi     85
2   3   Neha     50
3   4  Kiran     72
4   5  Meera     88

In [49]:
df.head()

   ID   Name  Score
0   1   Asha     78
1   2   Ravi     85
2   3   Neha     50
3   4  Kiran     72
4   5  Meera     88

In [51]:
df.shape

(5, 3)

In [52]:
df.columns

Index(['ID', 'Name', 'Score'], dtype='object')