In [1]:
# Name: Chhayank Sharma
# Registration no.: 60
# Demo given to introduce PANDAS for DAV lab

In [3]:
import pandas as pd
import numpy as np

In [4]:
df1 = pd.read_csv("ex1.csv")
df1

   a   b   c   d  message
0  1   2   3   4    hello
1  5   6   7   8    world
2  9  10  11  12      foo

In [6]:
df2 = pd.read_csv("ex2.csv", names=['a', 'b', 'c', 'd', 'message'])
df2

   a   b   c   d  message
0  1   2   3   4    first
1  5   6   7   8   second
2  9  10  11  12    third

In [10]:
df3 = pd.read_csv("ex3.csv", header=None)
df3

           0   1    2    3    4         5
0  something   a    b    c    d   message
1        one   1    2    3    4       NaN
2        two   5    6    7    8     hello
3      three   9   10   11   12     world

In [11]:
df3.isna()

       0      1      2      3      4      5
0  False  False  False  False  False  False
1  False  False  False  False  False   True
2  False  False  False  False  False  False
3  False  False  False  False  False  False

In [12]:
xlsx = pd.ExcelFile("Book1.xlsx")

In [13]:
xlsx.sheet_names

['Sheet1', 'Sheet2']

In [14]:
xl1=xlsx.parse(sheet_name="Sheet1")
xl2=xlsx.parse(sheet_name="Sheet2")

In [15]:
xl1

    abc  hello lmala
0   123  world  mkkk
1  aaaa  hhsaj  rwww

In [16]:
xl2

            abjcj aaaaaaa
0         asknkas  msakas
1  ksan ksanlasnn   masas
2         ksansak     kak

In [17]:
ser_x=pd.Series([4, 7, -5, -3])

In [18]:
ser_x

0    4
1    7
2   -5
3   -3
dtype: int64

In [19]:
ser_y=pd.Series([4, 7, -5, -3], index=['d', 'b', 'a', 'c'])

In [20]:
ser_y

d    4
b    7
a   -5
c   -3
dtype: int64

In [21]:
ser_y.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [22]:
ser_y['d']=0
ser_y

d    0
b    7
a   -5
c   -3
dtype: int64

In [23]:
ser_y[ser_y>0]

b    7
dtype: int64

In [24]:
dict_x={'abcd': 1234, 'efgh': 5678, 'ijkl': 9101112}

In [25]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
data_x=pd.DataFrame(data)

In [26]:
data_x

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [27]:
data_x['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [28]:
data_y=pd.DataFrame(np.arange(16).reshape(4,4))

In [29]:
data_y

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [30]:
data_y<10

       0      1      2      3
0   True   True   True   True
1   True   True   True   True
2   True   True  False  False
3  False  False  False  False

In [35]:
df3.sort_index()

           0   1    2    3    4         5
0  something   a    b    c    d   message
1        one   1    2    3    4       NaN
2        two   5    6    7    8     hello
3      three   9   10   11   12     world

In [36]:
df = pd.DataFrame()